import Head from "next/head";
import { uiActions } from "../store/slices/uiSlice";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import Modal from "../components/Modal";
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import Promotion from "../components/Promotion";
import Legals from "../components/Legals";
import Prefooter from "../components/Prefooter";
import Footer from "../components/Footer";

export default function Home({ ui }) {
  const dispatch = useDispatch();
  const language = useSelector((state) => state.ui.language);
  const content = useSelector((state) => state.ui.content);

  useEffect(() => {
    dispatch(uiActions.setUiContent(ui[language]));

    return () => {};
  }, [language]);

  if (Object.keys(content).length === 0) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Hoteles Xcaret</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Modal />
      <main>
        <Navbar />
        <Header />
        <section>
          <Promotion />
          <Promotion swap={true} />
          <Promotion />
        </section>
        <section>
          <Legals />
        </section>
        <section>
          <Prefooter />
        </section>
      </main>
      <Footer />
    </>
  );
}

export async function getStaticProps() {
  try {
    const data = await fetch(
      `https://raw.githubusercontent.com/javialcocer/test-json/main/data.json`
    );
    const json = await data.json();
    return {
      props: { ui: json },
    };
  } catch (error) {
    return {
      props: { ui: "error en la peticion" },
    };
  }
}
